### ISSUE TITLE
[IDF-6907] 7. Firmware burning fails on ESP32-S2

### ISSUE THREAD

**Issue by ustccw** [espressif/esp-launchpad#18] opened 2023-02-16 10:20 UTC
The test found that the ESP32-S2 can only burn at a baud rate lower than 921600, otherwise it will fail (the default baud rate of esp-launchpad is 921600, that is, it will fail to burn by default).

![p7](https://user-images.githubusercontent.com/24221485/219337310-f9456165-9330-4e22-9447-8e635d0ef781.png)

**Comment by igrr** [comment] 2023-02-16 10:31
Not 100% sure, but this might be fixed by https://github.com/espressif/esptool-js/pull/83.
@ustccw could you please go to https://espressif.github.io/esptool-js/ and try to flash the same binary to the same board? If that works, it mean that we will have a fix in esp-launchpad once the new esptool-js version is released.

**Comment by leeebo** [comment] 2023-03-02 04:15
> Not 100% sure, but this might be fixed by [espressif/esptool-js#83](https://github.com/espressif/esptool-js/pull/83). @ustccw could you please go to https://espressif.github.io/esptool-js/ and try to flash the same binary to the same board? If that works, it mean that we will have a fix in esp-launchpad once the new esptool-js version is released.

Can we trigger the deployment of the new version? since [esptool-js v0.2.1](https://github.com/espressif/esptool-js/releases/tag/v0.2.1) released 😃

**Comment by leeebo** [comment] 2023-05-29 07:43
@RushikeshPatange Has the problem been fixed? From my test, the issue still exists. You can reproduce it using the [link ](https://espressif.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/espressif/esp-dev-kits/master/launch.toml)

**Comment by RushikeshPatange** [comment] 2023-06-01 13:05
Hi @leeebo I have tested on my side using your [link](https://espressif.github.io/esp-launchpad/?flashConfigURL=https://raw.githubusercontent.com/espressif/esp-dev-kits/master/launch.toml).
- Used Devkit : ESP32-S3-WROOM-1 (as you mentioned ESP32-S3  Chip-typeset in your toml )
---
- It has been successfully flashed your binary for application type : `usb_otg_fac_1_0_2` on the same and I am not getting error of Timeout.
- If you still face issue regarding it, please raise issue on [esptool.js](https://github.com/espressif/esptool-js) (ESPLaunchpad is using esptool.js as library for flashing)

**Comment by leeebo** [comment] 2023-06-28 06:22
Hi @RushikeshPatange , Which OS are you using? we found it can work on Ubuntu and MacOS, but not work for Windows. (I am using Windows 11 Education 22H2)

**Comment by leeebo** [comment] 2023-06-29 02:14
@RushikeshPatange Seems Yes! on Windows for esp32s3 through `usb-serial-jtag` it works OK, but will block until timeout when through CP210x !

**Comment by RushikeshPatange** [comment] 2023-06-30 12:11
Let's wait for an update regarding this issue on the esptool-js side in their future release. 😄

**Comment by espressif2022** [comment] 2023-07-12 13:01
![image](https://github.com/espressif/esp-launchpad/assets/111102666/59156487-9528-418d-9a29-7901ca9d47d8)
@RushikeshPatange 
When I flash the ESP32-S3-BOX with USB, it blocked too, here is the log.
I manually enter boot mode before flashing.
OS: window 10 Education
WEB: chrome latest 114.0.5735.199（64 bit）

**Comment by lijunru-hub** [comment] 2023-07-12 13:12
I found that I was unsuccessful every time, on the old version of the box, I changed the edeg explorer and google explorer, neither of them could burn, this is the error message
![image](https://github.com/espressif/esp-launchpad/assets/68437239/cce6459b-c95d-4a72-b263-020a92ec81f6)

**Comment by espzav** [comment] 2023-07-13 10:17
@igrr I have a same issue with ESP32S3 (devkitC) on public launchpad and it is working on yours updated clone.

**Comment by igrr** [comment] 2023-07-13 10:18
Nice to hear that @espzav, thanks for trying! @lijunru-hub @espressif2022 could you please give it a try, as well?

**Comment by lijunru-hub** [comment] 2023-07-13 12:45
LGTM! All done

**Comment by igrr** [comment] 2023-07-16 19:29
Have create a PR: https://github.com/espressif/esp-launchpad/pull/28

**Closed** 2023-07-17 07:33 UTC
Labels: bug

**Comment by solomondong** [comment] 2024-01-12 06:56
Excuse me, does it support s3 / h2. launchpad?

**Comment by leeebo** [comment] 2024-01-13 13:07
@solomondong Yes, any chips that support `esptool` burning, should support launchpad burning also
